
title: Minjian Liu
url: 'https://github.com/Minjian/'
baseurl: '/Minjian.github.io' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6




#Profile information
name: Minjian Liu
#tagline: Embedded Systems Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: minjian.liu@jhu.edu
phone: (+1) 410-522-8408
linkedin: minjian
github: Minjian
#website: minjian.github.io #do not add http://
#twitter: '@twittername'
